### ISSUE TITLE
performance is amazing under org.gradle.parallel=true and org.gradle.configureondemand=true BUT it doesn't work

### ISSUE THREAD

**Issue by deanhiller** [Codearte/gradle-nexus-staging-plugin#25]
Great project though I have struggled getting through very cryptic messages and finally found out this plugin doesn't work with org.gradle.parallel either.

It seems to randomly create N repos and I have to turn these features off.  It was nice as it slammed uplaoding all my files in a multiproject build up to nexus really fast so my release didn't take long at all.  Now it takes forever with these properties off.

Once I disable the org.gradle.parallel feature (and the other one too), I finally get just a single nexus repo with all my jars.  Now on to trying to close and promote.

Also, I noticed promote does not depend on close?  Shouldn't there be a best effort to close before promotion?  just curious on that front.

**Comment by szpak** [comment]
Thanks for your feedback.

The main problem you mentioned is not related to gradle-nexus-staging-plugin. In fact this plugin doesn't impact artifacts upload anyway - it could be also execute from an another "empty" project to just close and/or promote already uploaded artifacts.

I don't know which plugin do you use - `maven` or `maven-publish`, nevertheless probably they both are not 'parallel compatible'. Recently I encountered similar issue working on CD mechanism for [Spock](https://github.com/spockframework/spock/pull/590). In case of close failure artifacts from the subsequent built (with another version number) were added to the already existing (and still open) repository.

I don't know if it is a limitation of Maven specification or just the upload plugin(s) in Gradle and I put a task to explain it on my (long) todo list recently. However, you could ask that question on the [forum](http://forums.gradle.org/) in the meantime. Maybe there is a workaround (just please put a link to the discussion here).

Why promote doesn't depend on close? Mostly to make it possible it rerun promotion without a need to create a new repository. As close & promote is a common use case the new `closeAndPromote` tasks exists (which under the hood just does it).

Btw, after solving issues with parallel upload my plugin should not stay on your way to have a quick release build. There is just one `closeAndPromote` task to be executed on the root project which can depend on every upload tasks.

**Comment by szpak** [comment]
Btw, keep in mind that uploading artifacts in general in parallel can be risky. Let's assume snapshot artifacts upload. The whole build can fail due to failing tests in one of the modules which some of artifacts have been already uploaded to the server. As a result you have inconsistent snapshot version released (only with selected artifacts). Building in parallel and uploading sequentially in the another Gradle execution can result the same, but the probability is much lower.
The good news is that using gradle-nexus-staging-plugin to finalize the production release it should not happen (close/promote action should wait for all upload operations to finish).
