### ISSUE TITLE
Support for parallel release of different projects in the same staging profile

### ISSUE THREAD

**Issue by atsakiridis** [Codearte/gradle-nexus-staging-plugin#45]
In the same packageGroup we handle a lot of artifacts. This means that if we try to `closeAndPromote` artifact C while we still have artifact A and B in the staging area, C will fail.

Isn't there a way in the `nexusStaging` closure to provide apart from packageGroup, also artifactId so that this issue is overcome?

**Comment by szpak** [comment]
No. However, after implementation of #36 (which is temporary disabled in 0.6.1 due to #44, but will be re-enabled in 0.7.0 when #21 is done) it would be possible to handle situation in which you have one open repository, but a lot of closed (e.g. because drop after release doesn't work). There is also a proposal to correlate uploaded artifacts with explicitly opened staging repository, however due to a limitation of Gradle it would probably still doesn't allow to upload artifacts from multiple projects simultaneously.

As a last resort if you want to do it manually (not from CI/CD server) there could be added a possibility to pass a staging repository ID. However, rather not in a configuration closure, but an execution parameter (`-PnexusStaging.repositoryId=...`).

**Comment by szpak** [comment]
Btw, I just reread your question and realized that you write about artifacts not projects. Do you really mean different artifacts from one projects (e.g. foo-1.0.0.jar, foo-1.0.0.zip, etc.) not different projects?

**Comment by atsakiridis** [comment]
@szpak thank you for your prompt answer.

I mean different artifacts from different projects, but which belong to the same maven groupId. So ultimately this boils down to Gradle limitation? If this is the case I can try to open an issue with Gradle folks

**Comment by szpak** [comment]
Gradle just uploads to different repositories and it's not aware of stagingRepository in Nexus (staging repository is created implicitly). It is described in #29. You may ask about that using [Gradle forum](https://discuss.gradle.org/). Maybe there is some configuration option I missed. Please share a link to the discussion here (or in #29) for a reference.

**Comment by atsakiridis** [comment]
Ok great will keep that in mind, thanks

**Comment by szpak** [comment]
Parallel releasing is implemented in gradle-nexus-staging-plugin 0.20.0, but will be fully functional after https://github.com/marcphilipp/nexus-publish-plugin/issues/11 is done.

**Comment by szpak** [comment]
With gradle-nexus-staging-plugin 0.20.0 and nexus-publish-plugin 0.2.0 it is possible to achieve. I enabled it for GNSP E2E tests on [Travis](https://travis-ci.org/Codearte/gradle-nexus-staging-plugin/builds/488298771).
