### ISSUE TITLE
Non-upload task named 'uploadArchives' crashes plugin

### ISSUE THREAD

**Issue by pettermahlen** [Codearte/gradle-nexus-staging-plugin#67]
We have a top-level `uploadArchives` task that aggregates the others in our multi-project build:

```
task uploadArchives(dependsOn: getTasksByName('uploadArchives', true))
```

Running even `check` (which shouldn't upload anything, AFAIU) causes Gradle to crash with the following stack trace:

```
org.codehaus.groovy.runtime.typehandling.GroovyCastException: Cannot cast object 'task ':uploadArchives'' with class 'org.gradle.api.DefaultTask_Decorated' to class 'org.gradle.api.tasks.Upload'
        at io.codearte.gradle.nexus.NexusStagingPlugin.tryToGetCredentialsFromUploadArchivesTask(NexusStagingPlugin.groovy:156)
        at io.codearte.gradle.nexus.NexusStagingPlugin$_tryToDetermineCredentials_closure4$_closure15.doCall(NexusStagingPlugin.groovy:133)
        at org.gradle.listener.ClosureBackedMethodInvocationDispatch.dispatch(ClosureBackedMethodInvocationDispatch.java:40)
```

It feels like it would be best to not just assume that all tasks called `uploadArchives` are in fact `Upload` instances?

**Comment by szpak** [comment]
Thanks for your report. I agree that there could be a check of a type, especially that is happens in the configuration phase. As an extension, an ability to point an upload task which should be used to get credentials from could be useful (e.g. for uploading only from submodules).

As a workaround please explicitly set username and passowrd to disable autodetection.

**Comment by szpak** [comment]
I've finally buckled down to fix that issue and the problem turned out to be more interesting. In a situation no stating tasks are requested to be executed that part should not be executed at all. I even had an integration test for that, however, I tested it with the "tasks" task, while the bug in the `*_Decorated` tasks classification doesn't occur there. In the end I added support for custom `uploadArchives` types and tune up assertions in my tests.

Thanks for taking time to report that issue.
