### ISSUE TITLE
Multiple staging profiles created on upload by Gradle in Travis causes closeRepository task to fail

### ISSUE THREAD

**Issue by pavolloffay** [Codearte/gradle-nexus-staging-plugin#76]
Hi,

we are having issues to use this plugin when VM (travis) changes public IP during the release.

From https://help.sonatype.com/repomanager2/staging-releases/managing-staging-repositories

>  A separate staging repository is created for every combination of User ID, IP Address, and User Agent

This jira https://issues.sonatype.org/browse/OSSRH-19485?focusedCommentId=340094&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-340094 advices to use profile id. 

We have added `stagingProfileId` to our gradle config however the build still fails e.g. 
https://travis-ci.org/jaegertracing/jaeger-client-java/jobs/441639782#L775
and it still creates multiple staging repositories:
![screenshot of nexus repository manager](https://user-images.githubusercontent.com/5618424/46955868-3ce24880-d094-11e8-877c-cc740733332a.png)

Here is out gradle config https://github.com/jaegertracing/jaeger-client-java/blob/master/build.gradle#L87
and also https://github.com/jaegertracing/jaeger-client-java/blob/master/gradle/publish.gradle. 

Any help is appreciated.

**Comment by szpak** [comment]
It's a big problem, I'm also not able to automatically release my project using Travis. In fact, it happens in the upload phase (multiple staging repositories are created) and `closeRepository` only visualize a problem. It affects also one-thread execution, even for a single module projects. I don't know how it could be solved at the gradle-nexus-staging-plugin level (merging staging repositories via API is not an option :) ).

Unfortunately Travis is [unlikely](https://github.com/travis-ci/travis-ci/issues/9555#issuecomment-428799836) to fix it on their side. There is an open [issue](https://github.com/gradle/gradle/issues/5711) for Gradle. You can comment there, as it seems to be a good place to fix it (it would be possible for gradle-nexus-staging-plugin to track one particular staging repository not to check number of them in a given state).

Update. I changed the title to more accurate.

**Comment by szpak** [comment]
For desperate hearts, there is a workaround [available](https://github.com/gradle/gradle/issues/5711#issuecomment-430170888) by @jakubhava.

**Comment by szpak** [comment]
It works fine with [nexus-publish-plugin](https://github.com/marcphilipp/nexus-publish-plugin/).

I updated the project FAQ to address it. A copy-paste for people hitting that issue.

To cut a long story short:
 - Gradle does [not support](https://github.com/gradle/gradle/issues/5711) uploading/publishing to explicitly created staging repositories in Nexus
 - gradle-nexus-staging-plugin had been using heuristics to find the right implicitly created staging repository in Nexus (which - with some limitations - worked fine in most cases)
 - Travis changed their infrastructure in autumn 2018 which [resulted](https://github.com/travis-ci/travis-ci/issues/9555#issuecomment-428799836) in using different IP addresses for the same build and - as a result - creation of multiple implicitly created staging repositories on upload/publishing for the same build
 - Marc Philipp created [nexus-publish-plugin](https://github.com/marcphilipp/nexus-publish-plugin/) to enhance publishing in Gradle which seamlessly integrates with gradle-nexus-staging-plugin and "fixes" a problem

For releasing from Travis (and in general) it's recommended to add [nexus-publish-plugin](https://github.com/marcphilipp/nexus-publish-plugin/) to your project and use its `publishToNexus` task to upload/publish artifacts to Nexus (instead of vanilla `publish...` from Gradle). It integrates seamlessly with gradle-nexus-staging-plugin to release to Maven Central (especially with 0.20.0+) - no other changes are required. What's more, with that [enhancement](https://github.com/marcphilipp/nexus-publish-plugin/issues/11) implemented the releasing to Nexus will be even more reliable
(e.g. an ability to run multiple releases for the same staging profile).

However, there is one caveat. `uploadArchives` from the `maven` plugin is [not supported](https://github.com/marcphilipp/nexus-publish-plugin/issues/8) by nexus-publish-plugin (only `publish...` from `maven-publish`).
