### ISSUE TITLE
deprecation of the staging repository id heuristic

### ISSUE THREAD

**Issue by Vampire** [Codearte/gradle-nexus-staging-plugin#84]
Maybe this is more of a question, but is there a reason to deprecate the heuristics to find the staging repository to work on?
Isn't it also a normal use-case to not have it available?
E. g. you either just do the publishing or maybe publishing and closing in a CI build but do the actual releasing of the build manually after verifying the result by calling the `releaseRepository` task.
In this case the `stagingRepositoryId` will not be set.
Or would you expect the `nexus-publish-plugin` in this case to inject somehow the id of the last time a staging repository was created into your plugin?
I'd say this might be even less reliable in case some manual action happened inbetween to the staging repositories.
Or would you then try to close the repository with the given ID if it exists and fall back to the heuristics if the repository is not present?

**Comment by szpak** [comment]
Thanks for your input. From the beginning GNSP and its tasks were separated from the uploading/publishing stage. I liked it very much, but it came with a quite important limitation. The mechanism to find the implicitly created staging repository needs to have just one staging repository in a given state. It means no parallel releasing of application using the same staging profile (people complained about that) and fragility in a case of error (the repositories are not automatically removed quite long) (also a known issue).

With the Marc's nexus-publish-plugin it has started to be possible to create a staging repository implicitly which (by the way) fixes the issue with uploading form Travis after their infrastructure change.

As I mentioned in the release notes I don't plan to remove the already existing code (there is just a warning that the mechanism would be more reliable with staging repository id set), but to be effectively able to test my plugin in e2e tests for Java 8 and 11 I need use the explicitly created stating repositories. Before that I needed to take care to do not push to different branches in the same time to do not fail the Travis builds. As a result I cannot officially support that approach.

Assuming manual actions it's still possible to set a value for a staging repository ID with `-P` - it's just a field in the plugin extension - with the minor add-on in the `build.gradle`. One would just need to get the and dump somewhere a staging repository id from the previous step to make it more automatically. In my projects I do closing and releasing steps separately - with a push to github and/or publish portal done in the meantime. However, it's still one Gradle execution.

To wrap it up. The old mechanism is in place (as a fallback), but due to e2e testing issues I cannot effectively test it and - as a result - officially support it. Feel free, however, to provide suggestion what - in your opinion - could be improved in that field.
